---
name: Code Lint

on:
  pull_request:

jobs:
  lint:
    name: tflint / python lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      
      - name: GCP TF lint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.gh_token }}
          working_directory: "terraform" 
          reporter: github-pr-review 
          fail_on_error: "true" 
          filter_mode: "nofilter" 
          tflint_rulesets: "google" 

      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "main.py"
          pylint-options: "--rcfile=.pylintrc"
          mypy-options: "--ignore-missing-imports --no-color-output --pretty"
        continue-on-error: true
